language: node_js
node_js:
- stable
script: npm test
deploy:
  provider: heroku
  api_key:
    secure: cv9cisrITMgPYZXEMRZSPEZdemUcyS7q9ZllYI79TwKgaxbiH3n02BNMjRjDENM4/n87fs0sTrHcpgrMcKhJY52uIcK2qtwMoBF/5E+SVbgSoRoai5lHbOB+Xl3+sgT7TwI7nc4y5ecFbhlxiqSFNAjDtOvzJALVtRJgQ0Hm78AnvGTpnQWdy99r/SupH+oBL5312jv4Bfayydu5JE0wdVbhOWuLesK4DwDtZXXpkBgXPBB+OJ9K7Uw2gcQMtP2ME3MmBXtOVBhJs4sB90e8Qq5hDvnPBJEM4+XCaiQw/5sgMvIUAk8vwqxQeey0Nd5lUE6I1mYOG4DkMujKat6RGf0PFh8ZZ+XnoIsO5UKqpRLkw8/nKyrBo7FUQbhMJ7VsUyqpnlsE8cEmdXUj76ZvbgA6p5CXeimjQ7rx1forMy5lu3+YkxbUNRiJirkxYwNF7hPgpVU99PYHC/88QZK4Q8UR0oWbetyO1dlWWJH+a/8mazoD9/zs7Y42exBrm+7spkb9inECmkGMCAAD58tfyLSBYf6RojJlYNvz3qwvgg5FuWEH/3valiJWhvHzRGjmDlxvzzVCco2ppnuXApw0iJzqXc2r+liv2xlPehyZ8aMQepJP7O2d83Njq/Z1G2MiK327wSk4aasU0F/r9xkn7uSlf3VCEz1Zpfe2VSTK/G0=
  app: Asteroids
  on:
    repo: LiamDotPro/Asteroids