language: node_js
node_js:
- stable
install:
  - npm install -g codecov
  - npm install -g mocha
  - npm install -g chai
  - npm install
script: 
- istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
- codecov